version: "2"

run:
  modules-download-mode: mod

linters:
  default: none
  enable:
    # Core quality
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - unconvert
    - revive
    # Security & correctness
    - gosec
    - errname
    - errorlint
    - nilerr
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    # Complexity
    - cyclop
    - gocognit
    - gocyclo
    - funlen
    - nestif
    # Code hygiene
    - goconst
    - dupl
    - prealloc
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 100
    funlen:
      lines: 80
      statements: 40
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    nestif:
      min-complexity: 4
    gocritic:
      disabled-checks:
        - ifElseChain
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters: [gocognit, gocyclo, cyclop, funlen, nestif, dupl]
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
