name: Bug Report
description: Report a bug in agentrun
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      render: go
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Output of `go version`
      placeholder: go1.24.0 linux/amd64
    validations:
      required: true

  - type: input
    id: agentrun-version
    attributes:
      label: agentrun version
      description: Output of `go list -m github.com/dmora/agentrun`
      placeholder: v0.1.0
    validations:
      required: true
